# Generated by Django 6.0.2 on 2026-02-05 10:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MarketStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_symbol', models.CharField(max_length=20, unique=True)),
                ('last_price', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('volume_24h_quote', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('high_24h', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('low_24h', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('trades_24h', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
