# Generated by Django 6.0.2 on 2026-02-05 10:29

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_symbol', models.CharField(max_length=20)),
                ('side', models.CharField(max_length=4)),
                ('type', models.CharField(default='LIMIT', max_length=10)),
                ('price', models.DecimalField(decimal_places=8, max_digits=28)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('filled_amount', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_symbol', models.CharField(max_length=20)),
                ('price', models.DecimalField(decimal_places=8, max_digits=28)),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28)),
                ('taker_side', models.CharField(max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
