# Generated by Django 6.0.2 on 2026-02-05 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trading', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='trade',
            name='buy_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades_as_buyer', to='trading.order'),
        ),
        migrations.AddField(
            model_name='trade',
            name='sell_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trades_as_seller', to='trading.order'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['market_symbol', 'side', 'status', 'price', 'created_at'], name='trading_ord_market__61cb23_idx'),
        ),
        migrations.AddIndex(
            model_name='trade',
            index=models.Index(fields=['market_symbol', 'created_at'], name='trading_tra_market__7ec8cc_idx'),
        ),
    ]
